### ISSUE TITLE
build.sh fails, method call fails

### ISSUE THREAD

**Issue by mgineer85** [shopwareLabs/SwagMediaS3#21]
```
michael@michael-linux:~/webdev/custom/plugins/SwagMediaS3$ ./build.sh 
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aws/aws-sdk-php 3.32.6 -> satisfiable by aws/aws-sdk-php[3.32.6].
    - aws/aws-sdk-php 3.32.6 requires guzzlehttp/guzzle ^5.3.1|^6.2.1 -> no matching package found.
  Problem 2
    - Installation request for league/flysystem-aws-s3-v3 1.0.13 -> satisfiable by league/flysystem-aws-s3-v3[1.0.13].
    - league/flysystem-aws-s3-v3 1.0.13 requires league/flysystem ~1.0 -> no matching package found.


  adding: SwagMediaS3/ (stored 0%)
  adding: SwagMediaS3/SwagMediaS3.php (deflated 60%)
  adding: SwagMediaS3/README.rst (deflated 50%)
  adding: SwagMediaS3/composer.json (deflated 47%)
  adding: SwagMediaS3/.gitignore (stored 0%)
  adding: SwagMediaS3/LICENSE (deflated 42%)
  adding: SwagMediaS3/build.sh (deflated 48%)
  adding: SwagMediaS3/plugin.xml (deflated 41%)
  adding: SwagMediaS3/composer.lock (deflated 82%)
```

so i tried again with
composer update --lock
and
composer install
afterwards

then it seems to finish pulling in the dependencies, but the plugin seems to be broken. here is the xdebug-errormessage, I get when I try to open the plugin manager. loading the pluginmanager fails then:

```
Fatal error: Uncaught TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /home/michael/webdev/custom/plugins/SwagMediaS3/vendor/guzzlehttp/guzzle/src/Client.php on line 89 and defined in /home/michael/webdev/custom/plugins/SwagMediaS3/vendor/guzzlehttp/guzzle/src/Client.php on line 128
```

here the same problem was reported already: https://forum.shopware.com/discussion/comment/218672/#Comment_218672  and https://github.com/guzzle/guzzle/issues/1994

**Comment by mgineer85** [comment]
hi, the errors regarding to the old version of the .lock-file is because the latest .lock-file was not commited to the master before creating the 2.0.0-tag: see https://github.com/shopwareLabs/SwagMediaS3/tree/v2.0.0  the lock-file is 9 month old, while the composer.json is only 3 month young.

adding a new tag to the current master fixed the problem with build.sh not running through. 

nevertheless, the fatal error with the plugin installed remains...

**Comment by teiling88** [comment]
> nevertheless, the fatal error with the plugin installed remains...

I think this commit causes your guzzle issue https://github.com/shopwareLabs/SwagMediaS3/commit/8ff8566d58b2c2a6198b7ea9d0d2da4a61361acd. Can you add again the replace part in your composer.json file and try it again?

**Comment by mgineer85** [comment]
no success unfortunately.
I added the replace-lines as they were before the mentioned commit. afterwards I committed the changes and added a new tag (v2.0.3) so build.sh would use the currentmost version. the result is the error below:

```
michael@michael-linux:~/webdev/swagtest$ ./build.sh
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for shopwarelabs/swag-media-s3 dev-master -> satisfiable by shopwarelabs/swag-media-s3[dev-master].
    - don't install guzzlehttp/guzzle 6.3.0|remove shopwarelabs/swag-media-s3 dev-master
    - Installation request for guzzlehttp/guzzle 6.3.0 -> satisfiable by guzzlehttp/guzzle[6.3.0].

  adding: SwagMediaS3/ (stored 0%)
  adding: SwagMediaS3/SwagMediaS3.php (deflated 60%)
  adding: SwagMediaS3/README.rst (deflated 50%)
  adding: SwagMediaS3/composer.json (deflated 50%)
  adding: SwagMediaS3/.gitignore (stored 0%)
  adding: SwagMediaS3/LICENSE (deflated 42%)
  adding: SwagMediaS3/build.sh (deflated 48%)
  adding: SwagMediaS3/plugin.xml (deflated 41%)
  adding: SwagMediaS3/composer.lock (deflated 84%)
```

I'm not familiar with composer. From guesswork I thought 
composer update 
or
composer update --lock 
might be helpful or at least don't harm. It doesn't change anything... Am I doing something wrong?

Thanks.

**Comment by mgineer85** [comment]
here another post I just found, might be very related to the issue here?
https://github.com/guzzle/guzzle/issues/1771

**Comment by shopwarrior** [comment]
Hello guys,
I tried to install this plugin, but all the time got same issue:
public_html/custom/plugins/SwagMediaS3$ ./build.sh 
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aws/aws-sdk-php 3.32.6 -> satisfiable by aws/aws-sdk-php[3.32.6].
    - aws/aws-sdk-php 3.32.6 requires guzzlehttp/guzzle ^5.3.1|^6.2.1 -> no matching package found.
  Problem 2
    - Installation request for league/flysystem-aws-s3-v3 1.0.13 -> satisfiable by league/flysystem-aws-s3-v3[1.0.13].
    - league/flysystem-aws-s3-v3 1.0.13 requires league/flysystem ~1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
  adding: SwagMediaS3/ (stored 0%)
  adding: SwagMediaS3/composer.json (deflated 47%)
  adding: SwagMediaS3/build.sh (deflated 48%)
  adding: SwagMediaS3/LICENSE (deflated 42%)
  adding: SwagMediaS3/plugin.xml (deflated 41%)
  adding: SwagMediaS3/README.rst (deflated 50%)
  adding: SwagMediaS3/.gitignore (stored 0%)
  adding: SwagMediaS3/composer.lock (deflated 82%)
  adding: SwagMediaS3/SwagMediaS3.php (deflated 60%)

Can someone update composer requirements?

**Comment by OeRnY** [comment]
@shopwarrior Until my merge request has been processed and a new build has been generated, you can refer to [my fork](https://github.com/OeRnY/SwagMediaS3/tree/sw54-compability) and build a new version of the plugin via
```bash
./build.sh sw5-compability
```
It would only work for shopware 5.4.x versions, though.

**Comment by sydetion** [comment]
Feb. 2019 and the issue still is existing, we are currently at shopware 5.6.x ... 
@janbuecker is further work on that topic planned or is this plugin generally no longer "supported" / recommended for productive usage

**Comment by shyim** [comment]
@sydetion This Plugin is not required anymore since Shopware 5.5
